### ISSUE TITLE
OpenSCAD 2019.5 + puzzlecad 1.3 rendering bug

### ISSUE THREAD

**Issue by ursoft** [aaron-siegel/puzzlecad#4]
burr_piece(
["xxx|xxx|xxx|xxx|xxx|xxx|.x.","xxx|xxx|xxx|xxx|xxx|xxx|.x.","xxx|xxx|xxx|xxx|xxx|xxx|...","xxx|xxx|xxx|...|...|...|...","xxx|xxx|xxx|...|...|...|...","xxx|xxx|xxx|...|...|...|...","xxx|xxx|xxx|...|...|...|...","..x{connect=mz+,clabel=Dy-}|x{connect=mz+,clabel=Dy-}x{connect=mz+,clabel=Dy-}x|xxx|...|...|...|...","...|..x|xxx|...|...|...|..."] // S05-L1
);

ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Nef_S2/SM_const_decorator.h Line: 329

**Comment by aaron-siegel** [comment]
This issue should be fixed in puzzlecad 2.0 beta, which is now publicly available on Thingiverse.
