### ISSUE TITLE
v2.3 packing_box() $auto_layout

### ISSUE THREAD

**Issue by ninjabunny** [aaron-siegel/puzzlecad#53]
autolayout blows up if its true. i guess its not a huge issue, but i would have to manually create the box
```
include <puzzlecad.scad>
require_puzzlecad_version("2.3");

packing_box([

    "xxxxx|xxxxx|..x{components={x+,y-}}xx|...xx|...xx",

    "xxxxx|x...x|....x|....x|...xx",

    "xxx{components={x-,z-}}..|x....|x...x{components={y+,z-}}|x...x|xxxxx",

    "xx...|xx...|xxx{components={x-,y+}}..|xxxxx|xxxxx"

], $burr_scale = 17, $box_wall_thickness = 6, $auto_layout = true);
```

**Comment by aaron-siegel** [comment]
Fixed on https://github.com/aaron-siegel/puzzlecad/pull/55
Will be merged into the next release.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/2014957/165826044-32b7b4bc-e6c1-4831-88aa-e3a7c4f99326.png">
